export const defaultProjects = [
  {
    _id: 'default-proj-1',
    title: 'Ludo Binge - Real-time Multiplayer Mobile App',
    description: 'High-performance cross-platform mobile board game with real-time multiplayer socket events, custom dice physics, dynamic audio synthesizers, offline AI bot engine, and optimized Google Play App Bundle packaging.',
    image: '',
    technologies: ['React Native', 'Expo SDK 57', 'TypeScript', 'Audio Engine', 'WebSockets', 'Android AAB', 'Gradle'],
    link: '',
    github: 'https://github.com/shivamShankhdhar/ludo-binge',
    startDate: '2026-08-01',
    featured: true,
    projectType: 'Mobile',
    badge: 'Play Store Ready',
    highlights: ['60 FPS Native Board Loop', 'Real-time WebSocket Multiplayer', 'Smart Offline AI Engine'],
  },
  {
    _id: 'default-proj-2',
    title: 'Chess Binge - Grandmaster AI & Competitive Play',
    description: 'Grandmaster-level competitive chess application built with custom visual chess piece themes, tactical move validation algorithms, deep multi-depth engine analysis, and native Android release signing.',
    image: '',
    technologies: ['React Native', 'Expo', 'Chess Engine', 'TypeScript', 'Tailwind', 'Android SDK'],
    link: '',
    github: 'https://github.com/shivamShankhdhar/chess-binge',
    startDate: '2026-07-15',
    featured: true,
    projectType: 'Mobile',
    badge: 'v2.0.2 Published',
    highlights: ['Multi-depth Position Analysis', 'Haptic Piece Snapping', 'Production Release v2.0.2'],
  },
  {
    _id: 'default-proj-3',
    title: 'Enterprise Developer Portfolio & CMS Engine',
    description: 'Bespoke high-performance developer portfolio platform featuring Next.js 16 App Router, dual Dark Red/Black & Red/White design systems, full MongoDB CRUD admin dashboard, and visitor messaging inbox.',
    image: '',
    technologies: ['Next.js 16', 'React 19', 'TypeScript', 'Tailwind CSS', 'MongoDB', 'Mongoose'],
    link: 'https://shivamshankhdhar.dev',
    github: 'https://github.com/shivamShankhdhar/portfolio',
    startDate: '2026-06-01',
    featured: true,
    projectType: 'Web',
    badge: 'Production Live',
    highlights: ['Dark Red & Black Theme System', 'Full MongoDB Admin Panel', 'Sub-second Turbopack Load'],
  },
  {
    _id: 'default-proj-4',
    title: 'High-Throughput Microservices & Auth Engine',
    description: 'Distributed backend architecture built with Spring Boot and Node.js microservices. Features JWT session orchestration, Redis caching, MongoDB replication, Docker compose clustering, and rate-limiting.',
    image: '',
    technologies: ['Java', 'Spring Boot', 'Node.js', 'PostgreSQL', 'Docker', 'Redis'],
    link: '',
    github: 'https://github.com/shivamShankhdhar',
    startDate: '2026-05-10',
    featured: false,
    projectType: 'Backend',
    badge: 'Microservices',
    highlights: ['High-throughput REST & WebSockets', 'Automated Docker Containers', 'ACID Transactions'],
  },
];

export const defaultSkills = [
  { _id: 's-1', name: 'React Native & Expo', category: 'Mobile', proficiency: 'Expert', icon: 'SiReact', experienceYears: '3+ Yrs', description: 'Cross-platform native iOS & Android apps, Hermes engine, Expo SDK 57, AAB release' },
  { _id: 's-2', name: 'Next.js 16 & React 19', category: 'Frontend', proficiency: 'Expert', icon: 'SiNextdotjs', experienceYears: '3+ Yrs', description: 'App Router, Server Components, SSR, Turbopack, and high-conversion landing engines' },
  { _id: 's-3', name: 'TypeScript', category: 'Languages', proficiency: 'Expert', icon: 'SiTypescript', experienceYears: '3+ Yrs', description: 'Deep strict type system architecture, generics, utility types, and API contract safety' },
  { _id: 's-4', name: 'Java & Spring Boot', category: 'Backend', proficiency: 'Advanced', icon: 'FaJava', experienceYears: '2+ Yrs', description: 'Enterprise backend services, RESTful API design, Spring Security, microservices' },
  { _id: 's-5', name: 'Node.js & Express', category: 'Backend', proficiency: 'Expert', icon: 'SiNodedotjs', experienceYears: '3+ Yrs', description: 'Asynchronous event loops, REST endpoints, real-time WebSocket communication' },
  { _id: 's-6', name: 'MongoDB & Mongoose', category: 'Databases', proficiency: 'Expert', icon: 'SiMongodb', experienceYears: '3+ Yrs', description: 'Document schemas, aggregation pipelines, replica set connection pooling, indexes' },
  { _id: 's-7', name: 'PostgreSQL & SQL', category: 'Databases', proficiency: 'Advanced', icon: 'SiPostgresql', experienceYears: '2+ Yrs', description: 'Relational data modeling, ACID transactions, complex joins, and query optimization' },
  { _id: 's-8', name: 'Tailwind CSS', category: 'Frontend', proficiency: 'Expert', icon: 'SiTailwindcss', experienceYears: '3+ Yrs', description: 'Bespoke design systems, micro-interactions, responsive dark/light color schemes' },
  { _id: 's-9', name: 'Docker & Containers', category: 'DevOps & Tools', proficiency: 'Intermediate', icon: 'SiDocker', experienceYears: '2+ Yrs', description: 'Containerized deployment, multi-stage Dockerfiles, Docker Compose networking' },
  { _id: 's-10', name: 'Git & GitHub Actions', category: 'DevOps & Tools', proficiency: 'Advanced', icon: 'SiGit', experienceYears: '3+ Yrs', description: 'Version control branching models, automated release pipelines, code review flows' },
  { _id: 's-11', name: 'Android Gradle & Build Tools', category: 'Mobile', proficiency: 'Advanced', icon: 'SiGradle', experienceYears: '2+ Yrs', description: 'Keystore generation, ProGuard rules, CMake C++ builds, AAB bundle generation' },
  { _id: 's-12', name: 'JavaScript (ES6+)', category: 'Languages', proficiency: 'Expert', icon: 'SiJavascript', experienceYears: '4+ Yrs', description: 'Event loops, functional programming, prototype chain, DOM, async architecture' },
];

export const defaultExperience = [
  {
    _id: 'exp-1',
    company: 'Independent Game Studio & Engineering Lead',
    position: 'Lead Mobile & Full Stack Engineer',
    description: 'Spearheading end-to-end architecture, UI design, game mechanics, and deployment of multi-platform mobile games (Ludo Binge, Chess Binge) and modern web engines.',
    startDate: '2024-01-01',
    endDate: '',
    isCurrentRole: true,
    technologies: ['React Native', 'Expo SDK 57', 'Next.js', 'Node.js', 'TypeScript', 'MongoDB', 'Gradle'],
    highlights: [
      'Engineered real-time multiplayer game mechanics, turn engines, and move validation with custom algorithms.',
      'Configured native Android signing, automated keystores, ProGuard rules, and generated optimized release AABs for Google Play.',
      'Architected full-featured Next.js developer portfolio with custom CMS admin panel and dual Dark/Light themes.',
    ],
  },
  {
    _id: 'exp-2',
    company: 'Enterprise Software Solutions',
    position: 'Full Stack Software Engineer',
    description: 'Developed scalable customer-facing web applications, integrated payment systems, and engineered high-throughput REST APIs with Java Spring Boot and Node.js.',
    startDate: '2022-06-01',
    endDate: '2023-12-31',
    isCurrentRole: false,
    technologies: ['Java', 'Spring Boot', 'React', 'TypeScript', 'PostgreSQL', 'Docker', 'Redis'],
    highlights: [
      'Designed microservice endpoints with Spring Boot & Node.js, reducing API response latency by 35%.',
      'Implemented robust JWT authentication pipelines and automated database migration schemas in PostgreSQL.',
      'Collaborated closely with cross-functional engineering teams using Agile Git workflows and CI/CD pipelines.',
    ],
  },
];

export const defaultEducation = [
  {
    _id: 'edu-1',
    school: 'APJ Abdul Kalam Technical University (AKTU)',
    degree: 'Bachelor of Technology (B.Tech)',
    field: 'Computer Science & Engineering',
    startDate: '2020-08-01',
    endDate: '2024-06-30',
    grade: 'First Class with Distinction',
    description: 'Comprehensive study of Algorithms, Data Structures, Distributed Computing, Database Management, and Object-Oriented Software Architecture.',
  },
];

export const defaultCertifications = [
  {
    _id: 'cert-1',
    title: 'Meta React Native Specialization',
    issuer: 'Meta (Coursera)',
    issueDate: '2024-03-15',
    credentialId: 'META-RN-2024-098',
    credentialUrl: 'https://coursera.org',
    description: 'Advanced mobile architecture, component lifecycle, animations, and cross-platform native deployment.',
  },
  {
    _id: 'cert-2',
    title: 'Full Stack Web Development with MERN',
    issuer: 'IBM',
    issueDate: '2023-11-20',
    credentialId: 'IBM-FS-8831',
    credentialUrl: 'https://coursera.org',
    description: 'Mastery in building end-to-end cloud-native microservices with Node, Express, MongoDB, and React.',
  },
  {
    _id: 'cert-3',
    title: 'Java Developer Certified Associate',
    issuer: 'Oracle',
    issueDate: '2023-05-10',
    credentialId: 'ORA-JAVA-5521',
    credentialUrl: 'https://oracle.com',
    description: 'In-depth proficiency in core Java design patterns, concurrency, algorithms, and OOP paradigms.',
  },
];

export const defaultApps = [
  {
    _id: 'default-app-chess',
    id: 'chess-binge',
    title: 'Chess Binge',
    subtitle: 'Grandmaster AI & Tactical Analysis',
    tagline: 'Competitive chess engineered with multi-depth move evaluations, customizable piece cosmetics, tactile haptics, and instant game state recovery.',
    category: 'Games',
    package: 'chess.binge',
    version: 'v2.0.2',
    status: 'Published on Google Play',
    rating: '4.9',
    ratingCount: '500+ Players',
    icon: '♟️',
    bannerType: 'chess',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=chess.binge',
    privacyUrl: '/mobile-apps/games/privacy-policy/chess-binge',
    technologies: [
      'React Native',
      'Expo SDK 57',
      'Chess Engine',
      'TypeScript',
      'Android AAB',
      'Google AdMob',
    ],
    highlights: [
      'Multi-Depth Position Analysis (Instant blunder & best-move evaluations)',
      'Haptic Piece Snapping with strict FIDE move-validation algorithms',
      'Local-First Offline Play with robust FEN board string recovery',
      'Custom Board & Piece Themes with Binge Coins progression',
      'Guaranteed Google AdMob Compliance with optional rewarded hint videos',
    ],
    features: [
      { label: 'Platform', value: 'Android 8.0+ (API 26+)' },
      { label: 'Bundle Format', value: 'Signed Android AAB' },
      { label: 'Engine AI', value: 'Multi-Depth Evaluation' },
      { label: 'Monetization', value: 'Google AdMob Compliant' },
    ],
    featured: true,
    order: 1,
  },
  {
    _id: 'default-app-ludo',
    id: 'ludo-binge',
    title: 'Ludo Binge',
    subtitle: 'Real-Time Multiplayer & Bot Arena',
    tagline: 'High-speed classic board game built with 60 FPS native board loops, custom dice physics, dynamic audio synthesizers, and adaptive AI bots.',
    category: 'Games',
    package: 'ludo.binge',
    version: 'v1.0.0',
    status: 'Play Store Ready',
    rating: '4.8',
    ratingCount: 'Early Access',
    icon: '🎲',
    bannerType: 'ludo',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=ludo.binge',
    privacyUrl: '/mobile-apps/games/privacy-policy/ludo-binge',
    technologies: [
      'React Native',
      'Expo SDK 57',
      'WebSockets',
      'Audio Engine',
      'TypeScript',
      'Google AdMob',
    ],
    highlights: [
      '60 FPS Native Board Loop with smooth pawn translation physics',
      'Real-Time WebSocket Multiplayer matchmaking engine',
      'Zero-Latency Offline AI Bots with adaptive tactical aggression',
      'Dynamic Audio Synthesizers & tactile haptic dice roll feedback',
      'Sandboxed Local Storage with zero account signup friction',
    ],
    features: [
      { label: 'Platform', value: 'Android 8.0+ (API 26+)' },
      { label: 'Bundle Format', value: 'Signed Android AAB' },
      { label: 'Multiplayer', value: 'WebSockets + Pass & Play' },
      { label: 'Sound FX', value: 'Dynamic Audio Synthesizer' },
    ],
    featured: true,
    order: 2,
  },
];

